/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * sqq-inscription API
 * OpenAPI spec version: 1.2.1-SNAPSHOT
 */
import type { Genre } from "./genre";

export interface BinomeDTO {
  id?: number;
  genre?: Genre;
  nom?: string;
  prenom?: string;
  adresse?: string;
  ville?: string;
  codePostal?: string;
  email?: string;
  telephone?: string;
  dateNaissance?: string;
}
