/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * sqq-inscription API
 * OpenAPI spec version: 1.0-SNAPSHOT
 */

export type CooperateurStatus =
  (typeof CooperateurStatus)[keyof typeof CooperateurStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CooperateurStatus = {
  PAYMENT_PENDING: "PAYMENT_PENDING",
  PAID: "PAID",
  PROCESSED: "PROCESSED",
} as const;
