/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * sqq-inscription API
 * OpenAPI spec version: 1.0-SNAPSHOT
 */
import type { Genre } from "./genre";
import type { CooperateurStatus } from "./cooperateurStatus";
import type { BinomeDTO } from "./binomeDTO";
import type { Instant } from "./instant";

export interface CooperateurDTO {
  id?: number;
  genre?: Genre;
  prenom?: string;
  nom?: string;
  telephone?: string;
  email?: string;
  adresse?: string;
  ville?: string;
  codePostal?: string;
  etudiantOuMinimasSociaux?: boolean;
  nombreDePersonnesDansLeFoyer?: number;
  parts?: number;
  partsDeSoutien?: number;
  acceptationDesStatus?: boolean;
  status?: CooperateurStatus;
  binome?: BinomeDTO;
  createdAt?: Instant;
  updatedAt?: Instant;
}
