/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * sqq-inscription API
 * OpenAPI spec version: 1.0-SNAPSHOT
 */
import type { Genre } from "./genre";

export interface CreateCooperateurDTO {
  genre?: Genre;
  prenom?: string;
  nom?: string;
  telephone?: string;
  email?: string;
  adresse?: string;
  ville?: string;
  codePostal?: string;
  etudiantOuMinimasSociaux?: boolean;
  nombreDePersonnesDansLeFoyer?: number;
  partsDeSoutien?: number;
  acceptationDesStatus?: boolean;
}
