/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * sqq-inscription API
 * OpenAPI spec version: 1.0-SNAPSHOT
 */

export type Genre = (typeof Genre)[keyof typeof Genre];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Genre = {
  MADAME: "MADAME",
  MONSIEUR: "MONSIEUR",
} as const;
