/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * sqq-inscription API
 * OpenAPI spec version: 1.2.1-SNAPSHOT
 */
import type { CooperateurStatus } from "./cooperateurStatus";

export type GetApiV1AdministrationPartsAdditionnellesParams = {
  statuses?: CooperateurStatus[];
};
