/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * sqq-inscription API
 * OpenAPI spec version: 1.2.1-SNAPSHOT
 */

export type GetApiV1AdministrationCooperateursParams = {
  page?: number;
  size?: number;
  search?: string;
};
