/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * sqq-inscription API
 * OpenAPI spec version: 1.2.1-SNAPSHOT
 */
import type { SouscriptionSupplementaireDTO } from "./souscriptionSupplementaireDTO";

export interface PageDTOSouscriptionSupplementaireDTO {
  content?: SouscriptionSupplementaireDTO[];
  page?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
  first?: boolean;
  last?: boolean;
}
