/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * sqq-inscription API
 * OpenAPI spec version: 1.2.1-SNAPSHOT
 */
import type { CooperateurDTO } from "./cooperateurDTO";

export interface PageDTOCooperateurDTO {
  content?: CooperateurDTO[];
  page?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
  first?: boolean;
  last?: boolean;
}
