/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * sqq-inscription API
 * OpenAPI spec version: 1.0-SNAPSHOT
 */

export type PostApiV1PartsAdditionnellesBody = {
  prenom?: string;
  nom?: string;
  email?: string;
  partsSupplementaires?: string;
};
