/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * sqq-inscription API
 * OpenAPI spec version: 1.0-SNAPSHOT
 */

export type PostApiV1RegistrationsBody = {
  genre?: string;
  prenom?: string;
  nom?: string;
  telephone?: string;
  email?: string;
  adresse?: string;
  ville?: string;
  codePostal?: string;
  etudiantOuMinimasSociaux?: string;
  nombreDePersonnesDansLeFoyer?: string;
  partsDeSoutien?: string;
  acceptationDesStatus?: string;
};
