/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * sqq-inscription API
 * OpenAPI spec version: 1.2.1-SNAPSHOT
 */
import type { CooperateurStatus } from "./cooperateurStatus";
import type { Instant } from "./instant";

export interface SouscriptionSupplementaireDTO {
  id?: number;
  uuid?: string;
  prenom?: string;
  nom?: string;
  email?: string;
  partsSupplementaires?: number;
  status?: CooperateurStatus;
  createdAt?: Instant;
  updatedAt?: Instant;
}
