/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * sqq-inscription API
 * OpenAPI spec version: 1.2.1-SNAPSHOT
 */
import * as axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  CooperateurDTO,
  GetApiV1AdministrationCooperateursParams,
  GetApiV1AdministrationPartsAdditionnellesParams,
  PostApiV1PartsSupplementairesBody,
  PostApiV1RegistrationsBody,
  SouscriptionSupplementaireDTO,
} from "../model";

export const getSqqInscriptionAPI = () => {
  /**
   * @summary List
   */
  const getApiV1AdministrationCooperateurs = <
    TData = AxiosResponse<CooperateurDTO[]>,
  >(
    params?: GetApiV1AdministrationCooperateursParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.get(`/api/v1/administration/cooperateurs`, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };

  /**
   * @summary Get
   */
  const getApiV1AdministrationCooperateursId = <
    TData = AxiosResponse<CooperateurDTO>,
  >(
    id: number,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.get(
      `/api/v1/administration/cooperateurs/${id}`,
      options,
    );
  };

  /**
   * @summary Archive Cooperateur
   */
  const postApiV1AdministrationCooperateursIdArchive = <
    TData = AxiosResponse<unknown>,
  >(
    id: number,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.post(
      `/api/v1/administration/cooperateurs/${id}/archive`,
      undefined,
      options,
    );
  };

  /**
   * @summary Mark As Processed
   */
  const postApiV1AdministrationCooperateursIdProcess = <
    TData = AxiosResponse<unknown>,
  >(
    id: number,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.post(
      `/api/v1/administration/cooperateurs/${id}/process`,
      undefined,
      options,
    );
  };

  /**
   * @summary List Souscriptions Supplementaires
   */
  const getApiV1AdministrationPartsAdditionnelles = <
    TData = AxiosResponse<SouscriptionSupplementaireDTO[]>,
  >(
    params?: GetApiV1AdministrationPartsAdditionnellesParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.get(`/api/v1/administration/parts-additionnelles`, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };

  /**
   * @summary Archive Souscription Supplementaire
   */
  const postApiV1AdministrationPartsAdditionnellesIdArchive = <
    TData = AxiosResponse<unknown>,
  >(
    id: number,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.post(
      `/api/v1/administration/parts-additionnelles/${id}/archive`,
      undefined,
      options,
    );
  };

  /**
   * @summary Mark Souscription Supplementaire As Processed
   */
  const postApiV1AdministrationPartsAdditionnellesIdProcess = <
    TData = AxiosResponse<unknown>,
  >(
    id: number,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.post(
      `/api/v1/administration/parts-additionnelles/${id}/process`,
      undefined,
      options,
    );
  };

  /**
   * @summary Register Form
   */
  const postApiV1PartsSupplementaires = <TData = AxiosResponse<unknown>>(
    postApiV1PartsSupplementairesBody: PostApiV1PartsSupplementairesBody,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    const formUrlEncoded = new URLSearchParams();
    if (postApiV1PartsSupplementairesBody.prenom !== undefined) {
      formUrlEncoded.append(`prenom`, postApiV1PartsSupplementairesBody.prenom);
    }
    if (postApiV1PartsSupplementairesBody.nom !== undefined) {
      formUrlEncoded.append(`nom`, postApiV1PartsSupplementairesBody.nom);
    }
    if (postApiV1PartsSupplementairesBody.email !== undefined) {
      formUrlEncoded.append(`email`, postApiV1PartsSupplementairesBody.email);
    }
    if (postApiV1PartsSupplementairesBody.partsSupplementaires !== undefined) {
      formUrlEncoded.append(
        `partsSupplementaires`,
        postApiV1PartsSupplementairesBody.partsSupplementaires,
      );
    }

    return axios.default.post(
      `/api/v1/parts-supplementaires`,
      formUrlEncoded,
      options,
    );
  };

  /**
   * @summary Successful Payment
   */
  const postApiV1PartsSupplementairesSuccessUuid = <
    TData = AxiosResponse<unknown>,
  >(
    uuid: string,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.post(
      `/api/v1/parts-supplementaires/success/${uuid}`,
      undefined,
      options,
    );
  };

  /**
   * @summary Register Form
   */
  const postApiV1Registrations = <TData = AxiosResponse<unknown>>(
    postApiV1RegistrationsBody: PostApiV1RegistrationsBody,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    const formUrlEncoded = new URLSearchParams();
    if (postApiV1RegistrationsBody.genre !== undefined) {
      formUrlEncoded.append(`genre`, postApiV1RegistrationsBody.genre);
    }
    if (postApiV1RegistrationsBody.prenom !== undefined) {
      formUrlEncoded.append(`prenom`, postApiV1RegistrationsBody.prenom);
    }
    if (postApiV1RegistrationsBody.nom !== undefined) {
      formUrlEncoded.append(`nom`, postApiV1RegistrationsBody.nom);
    }
    if (postApiV1RegistrationsBody.telephone !== undefined) {
      formUrlEncoded.append(`telephone`, postApiV1RegistrationsBody.telephone);
    }
    if (postApiV1RegistrationsBody.email !== undefined) {
      formUrlEncoded.append(`email`, postApiV1RegistrationsBody.email);
    }
    if (postApiV1RegistrationsBody.adresse !== undefined) {
      formUrlEncoded.append(`adresse`, postApiV1RegistrationsBody.adresse);
    }
    if (postApiV1RegistrationsBody.ville !== undefined) {
      formUrlEncoded.append(`ville`, postApiV1RegistrationsBody.ville);
    }
    if (postApiV1RegistrationsBody.codePostal !== undefined) {
      formUrlEncoded.append(
        `codePostal`,
        postApiV1RegistrationsBody.codePostal,
      );
    }
    if (postApiV1RegistrationsBody.etudiantOuMinimasSociaux !== undefined) {
      formUrlEncoded.append(
        `etudiantOuMinimasSociaux`,
        postApiV1RegistrationsBody.etudiantOuMinimasSociaux,
      );
    }
    if (postApiV1RegistrationsBody.nombreDePersonnesDansLeFoyer !== undefined) {
      formUrlEncoded.append(
        `nombreDePersonnesDansLeFoyer`,
        postApiV1RegistrationsBody.nombreDePersonnesDansLeFoyer,
      );
    }
    if (postApiV1RegistrationsBody.partsDeSoutien !== undefined) {
      formUrlEncoded.append(
        `partsDeSoutien`,
        postApiV1RegistrationsBody.partsDeSoutien,
      );
    }
    if (postApiV1RegistrationsBody.acceptationDesStatus !== undefined) {
      formUrlEncoded.append(
        `acceptationDesStatus`,
        postApiV1RegistrationsBody.acceptationDesStatus,
      );
    }
    if (postApiV1RegistrationsBody.binomeEnabled !== undefined) {
      formUrlEncoded.append(
        `binomeEnabled`,
        postApiV1RegistrationsBody.binomeEnabled,
      );
    }
    if (postApiV1RegistrationsBody.binomeGenre !== undefined) {
      formUrlEncoded.append(
        `binomeGenre`,
        postApiV1RegistrationsBody.binomeGenre,
      );
    }
    if (postApiV1RegistrationsBody.binomeNom !== undefined) {
      formUrlEncoded.append(`binomeNom`, postApiV1RegistrationsBody.binomeNom);
    }
    if (postApiV1RegistrationsBody.binomePrenom !== undefined) {
      formUrlEncoded.append(
        `binomePrenom`,
        postApiV1RegistrationsBody.binomePrenom,
      );
    }
    if (postApiV1RegistrationsBody.binomeAdresse !== undefined) {
      formUrlEncoded.append(
        `binomeAdresse`,
        postApiV1RegistrationsBody.binomeAdresse,
      );
    }
    if (postApiV1RegistrationsBody.binomeVille !== undefined) {
      formUrlEncoded.append(
        `binomeVille`,
        postApiV1RegistrationsBody.binomeVille,
      );
    }
    if (postApiV1RegistrationsBody.binomeCodePostal !== undefined) {
      formUrlEncoded.append(
        `binomeCodePostal`,
        postApiV1RegistrationsBody.binomeCodePostal,
      );
    }
    if (postApiV1RegistrationsBody.binomeEmail !== undefined) {
      formUrlEncoded.append(
        `binomeEmail`,
        postApiV1RegistrationsBody.binomeEmail,
      );
    }
    if (postApiV1RegistrationsBody.binomeTelephone !== undefined) {
      formUrlEncoded.append(
        `binomeTelephone`,
        postApiV1RegistrationsBody.binomeTelephone,
      );
    }
    if (postApiV1RegistrationsBody.binomeDateNaissance !== undefined) {
      formUrlEncoded.append(
        `binomeDateNaissance`,
        postApiV1RegistrationsBody.binomeDateNaissance,
      );
    }

    return axios.default.post(`/api/v1/registrations`, formUrlEncoded, options);
  };

  /**
   * @summary Successful Payment
   */
  const postApiV1RegistrationsSuccessUuid = <TData = AxiosResponse<unknown>>(
    uuid: string,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.post(
      `/api/v1/registrations/success/${uuid}`,
      undefined,
      options,
    );
  };

  /**
   * @summary Retry Cooperateur Payment
   */
  const postApiV1RetryPaymentCooperateurUuid = <TData = AxiosResponse<unknown>>(
    uuid: string,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.post(
      `/api/v1/retry-payment/cooperateur/${uuid}`,
      undefined,
      options,
    );
  };

  /**
   * @summary Get Cooperateur Payment Info
   */
  const getApiV1RetryPaymentCooperateurUuid = <TData = AxiosResponse<unknown>>(
    uuid: string,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.get(
      `/api/v1/retry-payment/cooperateur/${uuid}`,
      options,
    );
  };

  /**
   * @summary Retry Souscription Payment
   */
  const postApiV1RetryPaymentSouscriptionUuid = <
    TData = AxiosResponse<unknown>,
  >(
    uuid: string,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.post(
      `/api/v1/retry-payment/souscription/${uuid}`,
      undefined,
      options,
    );
  };

  /**
   * @summary Get Souscription Payment Info
   */
  const getApiV1RetryPaymentSouscriptionUuid = <TData = AxiosResponse<unknown>>(
    uuid: string,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.get(
      `/api/v1/retry-payment/souscription/${uuid}`,
      options,
    );
  };

  return {
    getApiV1AdministrationCooperateurs,
    getApiV1AdministrationCooperateursId,
    postApiV1AdministrationCooperateursIdArchive,
    postApiV1AdministrationCooperateursIdProcess,
    getApiV1AdministrationPartsAdditionnelles,
    postApiV1AdministrationPartsAdditionnellesIdArchive,
    postApiV1AdministrationPartsAdditionnellesIdProcess,
    postApiV1PartsSupplementaires,
    postApiV1PartsSupplementairesSuccessUuid,
    postApiV1Registrations,
    postApiV1RegistrationsSuccessUuid,
    postApiV1RetryPaymentCooperateurUuid,
    getApiV1RetryPaymentCooperateurUuid,
    postApiV1RetryPaymentSouscriptionUuid,
    getApiV1RetryPaymentSouscriptionUuid,
  };
};
export type GetApiV1AdministrationCooperateursResult = AxiosResponse<
  CooperateurDTO[]
>;
export type GetApiV1AdministrationCooperateursIdResult =
  AxiosResponse<CooperateurDTO>;
export type PostApiV1AdministrationCooperateursIdArchiveResult =
  AxiosResponse<unknown>;
export type PostApiV1AdministrationCooperateursIdProcessResult =
  AxiosResponse<unknown>;
export type GetApiV1AdministrationPartsAdditionnellesResult = AxiosResponse<
  SouscriptionSupplementaireDTO[]
>;
export type PostApiV1AdministrationPartsAdditionnellesIdArchiveResult =
  AxiosResponse<unknown>;
export type PostApiV1AdministrationPartsAdditionnellesIdProcessResult =
  AxiosResponse<unknown>;
export type PostApiV1PartsSupplementairesResult = AxiosResponse<unknown>;
export type PostApiV1PartsSupplementairesSuccessUuidResult =
  AxiosResponse<unknown>;
export type PostApiV1RegistrationsResult = AxiosResponse<unknown>;
export type PostApiV1RegistrationsSuccessUuidResult = AxiosResponse<unknown>;
export type PostApiV1RetryPaymentCooperateurUuidResult = AxiosResponse<unknown>;
export type GetApiV1RetryPaymentCooperateurUuidResult = AxiosResponse<unknown>;
export type PostApiV1RetryPaymentSouscriptionUuidResult =
  AxiosResponse<unknown>;
export type GetApiV1RetryPaymentSouscriptionUuidResult = AxiosResponse<unknown>;
